/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "bg-main": "#050814",
        "bg-secondary": "#0a0f1d",
        "bg-sidebar": "#050814",
        "bg-surface": "#101827",
        "bg-surface-elevated": "#111827",
        "color-primary": "#47FAF3",
        "color-primary-hover": "#32e0d9",
        "color-secondary": "#3B82F6",
        "text-primary": "#F8FAFC",
        "text-secondary": "#94A3B8",
        "text-muted": "#64748B",
        "on-surface-variant": "#c1c6d7",
        "on-secondary-container": "#005d5a",
        "secondary-fixed-dim": "#00ddd6",
        "on-error": "#690005",
        "on-tertiary-fixed": "#410004",
        "tertiary": "#ffb3ae",
        "primary-fixed": "#d8e2ff",
        "outline": "#8b90a0",
        "on-surface": "#dfe2f3",
        "surface-tint": "#aec6ff",
        "on-background": "#dfe2f3",
        "tertiary-container": "#dd3438",
        "surface-bright": "#353946",
        "surface-dim": "#0f131f",
        "on-secondary-fixed-variant": "#00504d",
        "on-secondary-fixed": "#00201f",
        "on-tertiary-fixed-variant": "#930014",
        "surface-container-high": "#262a37",
        "inverse-primary": "#0059c5",
        "inverse-on-surface": "#2c303d",
        "surface": "#0f131f",
        "primary-fixed-dim": "#aec6ff",
        "error-container": "#93000a",
        "on-primary-container": "#ffffff",
        "background": "#0f131f",
        "on-tertiary-container": "#ffffff",
        "tertiary-fixed-dim": "#ffb3ae",
        "primary-container": "#0070f3",
        "error": "#ffb4ab",
        "secondary-fixed": "#47faf3",
        "outline-variant": "#414754",
        "on-primary-fixed": "#001a43",
        "surface-container-lowest": "#0a0e1a",
        "surface-container": "#1b1f2c",
        "surface-container-low": "#171b28",
        "secondary": "#47faf3",
        "primary": "#aec6ff",
        "tertiary-fixed": "#ffdad7",
        "on-tertiary": "#68000b",
        "on-primary-fixed-variant": "#004397",
        "on-primary": "#002e6b",
        "secondary-container": "#00ddd6",
        "surface-container-highest": "#313442",
        "on-secondary": "#003735",
        "surface-variant": "#313442",
        "on-error-container": "#ffdad6",
        "inverse-surface": "#dfe2f3"
      },
      borderRadius: {
        "radius-sm": "4px",
        "radius-md": "8px",
        "radius-lg": "16px",
      }
    },
  },
  plugins: [],
  corePlugins: {
    preflight: false,
  }
}
